#!/bin/bash

if [[ $(uname -s) == *NT* ]]; then
    echo "This script is not intended to run on Windows"
elif [[ $(uname -s) == *Darwin* ]]; then
    echo "Support for Mac is not implemented yet"
else
    echo "Building for Linux"
    cargo build --release
    echo "Copying .desktop file to applications folder"
    cp assets/drive_af.desktop $HOME/.local/share/applications/
    echo "Everything is ready"
fi
